### ISSUE TITLE
pip installation fails

### ISSUE THREAD

**Issue by spring-haru** [mmngreco/IneqPy#10]
I use Anaconda and tried to install `IneqPy` using `pip`, but failed. The following is the error message in Terminal on Mac:

```
Collecting IneqPy
  Using cached https://files.pythonhosted.org/packages/74/79/cd12433cd2900da371ad88b1fb21fa03520b2890679748e1941b9c51fbd0/IneqPy-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ln/3f5j8t9d015gwnpdkpt68cpw0000gn/T/pip-install-ehxu8d3b/IneqPy/setup.py", line 3, in <module>
        description = open('README.rst').readlines()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ln/3f5j8t9d015gwnpdkpt68cpw0000gn/T/pip-install-ehxu8d3b/IneqPy/
```

**Comment by mmngreco** [comment]
Hi, thanks for report! Are you following the readme installation section?

**Comment by spring-haru** [comment]
I should have given you more details. Sorry. 
I tried to install `IneqPy` from `PyPI` using
```
pip install IneqPy
```
in Terminal on Mac. Is this supported?
I assumed it is because `IneqPy` can be found in [PyPI](https://pypi.org/project/IneqPy/).

**Comment by mmngreco** [comment]
Now I see it,  the PyPI index is outdated at this moment :disappointed: . Try using the github repository with the next code:

```
pip install git+https://github.com/mmngreco/IneqPy.git
```

**Comment by mmngreco** [comment]
Let me know if you have any other problem related with this.

**Comment by spring-haru** [comment]
Sorry for my belated reply. Installation went fine with no problem, following your suggestion.

I have another issue. I compared the gini values calculated from `IneqPy` and `pysal`, using the following code.  The result is that `IneqPy` gives higher values than `pysal` whenever I tried. I wonder if you could shed light on what I am missing here?

```
import numpy as np
import pandas as pd
from scipy.stats import lognorm
from pysal.explore.inequality.gini import Gini
from pysal.explore.inequality.theil import Theil
import ineqpy

n = 100
y = lognorm.rvs(s=1,size=n)
df = pd.DataFrame({'y':y,'w':np.ones(n)})

ineqpy.gini(income='y',weights='w',data=df), Gini(y).g
```

 BTW, the Theil values match.

**Comment by mmngreco** [comment]
Cool, it's good to hear that, I will close this current issue then. 

Would you mind open another issue for the new one ? 



Enviado desde mi iPhone
