### ISSUE TITLE
Rename ratio_top_rest

### ISSUE THREAD

**Issue by mmngreco** [mmngreco/IneqPy#35]
I'm planing to release a new version but first I would like rename `ratio_top_rest` by `top_rest_ratio` or just `top_rest` what do you think @daviddavo any complain about it?. The reason it's because it's not common to see "ratio" first, [for example sharpe ratio](https://github.com/ranaroussi/quantstats/blob/main/quantstats/stats.py#L271).

**Comment by daviddavo** [comment]
Yeah, I think top_rest is fine as it can be read the same as "top/rest"

**Comment by mmngreco** [comment]
Perfect, I will change it and then release the new version soon.
